# yaml-language-server: $schema=../../../schema/schemas/parameters/index.json

parameters:
  pns.publish.endpoint:
    type: string
    description: Notification service management API endpoint
    format: url
    default: ""
  pns.subscribe.endpoint:
    type: string
    description: Notification service websocket API endpoint
    format: url
    default: ""
