name: Test

on:
  push:
    branches:
      - develop
      - feature_functionMiddleware
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - run: npm i -g esbuild
      - run: npm install
      - run: npm test
